name: Daily Site Deploy

on:
  schedule:
    # Runs at 00:00 UTC daily
    - cron: '0 0 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    # Install dependencies and build your site here
    # For example, if it's a Next.js site:
    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build
      run: npm run export # For Next.js static export; adjust according to your build process

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out # The directory where your build script outputs the static files
